[profile.default]
libs = ["node_modules", "foundry/lib"]
out = "foundry/out"
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
  'eth-gas-reporter/=node_modules/eth-gas-reporter/',
  'hardhat/=node_modules/hardhat/',
  'forge-std/=lib/forge-std/src/',
]
src = "foundry/src"
test = 'foundry/test'
# https://book.getfoundry.sh/reference/config/solidity-compiler?highlight=warnings#deny_warnings
deny_warnings = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
